# Basic SSL enabled taky setup for oneliner install
version: "3.7"
services:
#This is responsible for routing messages
   taky-cot:
    image: skadakar/taky:0.8.3
    container_name: taky-cot
    user: "1000"
    network_mode: host
    ports:
      - 8089:8089
    restart: unless-stopped
    environment:
      - ssl_enabled=true
      - client_cert_required=true
      - mode=cot
      - public_ip=${IP}
      - hostname=${ID}
      - fqdnoverride=${IP}:8443
    volumes:
      - /root/taky-data/:/data
      
#This is responsible for routing data
   taky-data:
    image: skadakar/taky:0.8.3
    container_name: taky-data
    user: "1000"
    network_mode: host
    ports:
      - 8443:8443
    restart: unless-stopped
    environment:
      - ssl_enabled=true
      - client_cert_required=true
      - mode=data
      - public_ip=${ID}
      - hostname=${ID}
      - fqdnoverride=${IP}:8443
    volumes:
      - /root/taky-data/:/data
