version: "3.7"
services:
   taky-cot:
    image: skadakar/taky:0.8.2
    container_name: taky-cot
    user: "1000"
    network_mode: host
    ports:
      - 8087:8087
      - 8089:8089
    restart: unless-stopped
    environment:
      - ssl_enabled=true
      - client_cert_required=true
      - mode=cot
    volumes:
      - /root/taky-data/:/data
   taky-data:
    image: skadakar/taky:0.8.2
    container_name: taky-data
    user: "1000"
    network_mode: host
    ports:
      - 8080:8080
      - 8443:8443
    restart: unless-stopped
    environment:
      - ssl_enabled=true
      - client_cert_required=true
      - mode=data
    volumes:
      - /root/taky-data/:/data

